import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//styles
import global from "@/styles/global.module.scss"
import '@/styles/global.scss'
//components
import SideBar from "@/components/SideBar/SideBar";
import {Providers} from "@/redux/provider";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${global.body}`}>
      <SideBar/>
      <main className={global.main}>
          <Providers>
              {children}
          </Providers>
      </main>
      </body>
    </html>
  )
}
